name: ExplosiveMobs
version: ${project.version}
description: 'Let mobs explode once they die'
author: programie
website: https://selfcoders.com
main: com.selfcoders.explosivemobs.ExplosiveMobs
commands:
  spawnexplosivemob:
    description: 'Spawn an explosive mob in front of you or another player'
    usage: '/spawnexplosivemob <mob>:<type> <amount> <targetplayer>'
    permission: 'explosivemob.spawn'
permissions:
  explosivemobs.*:
    description: 'Gives access to all features'
    children:
      explosivemobs.spawn: true
      explosivemobs.spawn.target: true
  explosivemobs.spawn:
    description: 'Allows you to spawn an explosive mob'
    default: op
  explosivemobs.spawn.target:
    description: 'Allows you to spawn an explosive mob in front of another player'
    default: op
